### ISSUE TITLE
heroku:init generates a bad docker-compose.yml (gunicorn)

### ISSUE THREAD

**Issue by nkobber** [heroku/heroku-container-tools#125]
When i create a docker-compose.yml with heroku:init i get a wrong syntax in my docker-compose.yml

**Procfile**

    web: gunicorn --reload fussball.wsgi --log-file -

**Generated docker-compose.yml**

    web:
        ...
        command: 'bash -c ''gunicorn --reload fussball.wsgi --log-file -'''
        ...

Problem is that this is a wrong syntax for gunicorn and i get this error:

    web_1 | usage: gunicorn [OPTIONS] [APP_MODULE]
    web_1 | gunicorn: error: No application module specified.

**Comment by nikoradk** [comment]
The syntax may be right. It works if i remove the bash part.

**Comment by hunterloftis** [comment]
I think we discovered that this (the `bash -c` hack to get docker to allow env vars in commands) conflicted with gunicorn.

However, I don't believe there's an alternative method to enable stuff like `web: node serve -p $PORT`. Would love to be corrected on that.

/cc @stargaret @jkutner

**Comment by alanjds** [comment]
I got the same problem with uwsgi:

```
#Procfile
web: uwsgi uwsgi.ini
```
Gives me:
```
#docker-compose.yml
web:
  build: .
  command: 'bash -c ''uwsgi uwsgi.ini'''
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 8080
  ports:
    - '8080:8080'
  volumes:
    - '.:/app/user'
```

But seems that uwsgi is got called without arguments

**Comment by alanjds** [comment]
Specifically with uwsgi, I found a workaround:

```
#docker-compose.yml
web:
  build: .
  command: 'bash -c ''uwsgi'''
  working_dir: /app/user
  environment:
    PORT: 8080
    UWSGI_INI: uwsgi.ini
  ports:
    - '8080:8080'
...
```

But please fix this as soon as possible :/
