### ISSUE TITLE
Values from environement directive in docker-compose.yml are ignored

### ISSUE THREAD

**Issue by pirhoo** [heroku/heroku-container-tools#142]
Hej,

when I run a docker instance on heroku, my environment variables are ignored. 
Here is my docker-compose.yml (which work fine with `docker-compose run web`) :

```yml
web:
  build: .
  command: 'bash -c ''bundle exec puma -C config/puma.rb'''
  working_dir: /app/user
  environment: &ENV
    PORT: 8080
    MAILTRAP_API_TOKEN:  <MYSTERY>
    TWITTER_API_KEY: <MYSTERY>
    TWITTER_API_SECRET: <MYSTERY>
  ports:
    - '8080:8080'
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    <<: *ENV
  ports:
    - '8080:8080'
  volumes:
    - '.:/app/user'
```

Did I miss something? As discussed on [Stack Overflow](http://stackoverflow.com/questions/34811953/transmit-heroku-environement-variables-to-docker-instance), it would have been very helpful to be able to replicate those environment variables automatically in the docker instance :)

All best
