### ISSUE TITLE
heroku container:init not working

### ISSUE THREAD

**Issue by jonchay** [heroku/heroku-container-tools#163]
I'm following the tutorial to build an application with Docker and Heroku [here](https://devcenter.heroku.com/articles/local-development-with-docker#initialize-local-container-configuration-for-the-app) and the command `heroku container:init` doesn't seem to be a supported command.

I also notice that `heroku-container-tools` is on v3.0.0. Is there any documentation on how to initialize?

**Comment by fotos** [comment]
The commands were dropped in #158 and the documentation (Heroku, README) is outdated.

If you want a generated file you can do the following:

1. [Setup the project locally](https://github.com/heroku/heroku-container-tools#developing-and-contributing)
2. git reset --hard 8201e04e0c7974ce20efe2c1658ef6b6b898c367
3. npm install
4. heroku plugins:link .

and then in your project you can:

```
heroku container:init
```

The generated Dockerfile is like this:
```Dockerfile
FROM heroku/ruby
```

and `docker-compose.yml`:

```
web:
  build: .
  command: 'bash -c ''bundle exec puma -C config/puma.rb'''
  working_dir: /app/user
  environment:
    PORT: 8080
    DATABASE_URL: 'postgres://postgres:@herokuPostgresql:5432/postgres'
  ports:
    - '8080:8080'
  links:
    - herokuPostgresql
shell:
  build: .
  command: bash
  working_dir: /app/user
  environment:
    PORT: 8080
    DATABASE_URL: 'postgres://postgres:@herokuPostgresql:5432/postgres'
  ports:
    - '8080:8080'
  links:
    - herokuPostgresql
  volumes:
    - '.:/app/user'
herokuPostgresql:
  image: postgres
```

Besides updating the documentation it would be nice to tag the (2.x and 3.x) releases as well. 😄
